# Use the official PostgreSQL image with the desired version
FROM postgres:latest

ARG POSTGRES_PASSWORD

# Set environment variables for database configuration
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=games

# Copy any initialization SQL scripts to the container
COPY games-init.sql /docker-entrypoint-initdb.d/
