steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'generate']
    secretEnv:
      - 'PG_AE_URL'

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: "gcr.io/cloud-builders/gcloud-slim"
    args: [
      "storage",
      "cp",
      "--recursive",
      "dist",
      'package.json',
      'gs://bgdk-build-for-deploy'
    ]

    # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', 'api.yaml']

serviceAccount: aklapper@games-424800.iam.gserviceaccount.com

availableSecrets:
  secretsManager:
  - versionName: projects/games-424800/secrets/PG_AE_URL/versions/latest
    env: 'PG_AE_URL'

# Store logs in bucket
logsBucket: 'gs://logs-cloudbuild'
options:
  logging: LEGACY

# Optional: Define a timeout for the build
timeout: '1600s'

