steps:

  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'generate']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'lint']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'test']

    # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', 'api.yaml']

serviceAccount: aklapper@games-424800.iam.gserviceaccount.com

logsBucket: 'gs://logs-cloudbuild'
options:
  logging: LEGACY

artifacts:
  objects:
    location: 'gs://bgdk-build-for-deploy'
    paths: ['*.*']
# Optional: Define a timeout for the build
timeout: '1500s'

