steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'generate']
    env:
      - 'PG_AE_URL=${_PG_AE_URL}'

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'lint']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'test']
    env:
      - 'PG_AE_URL=${_PG_AE_URL}'

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'PG_AE_URL=${_PG_AE_URL}'

  - name: "gcr.io/cloud-builders/gcloud-slim"
    args: [
      "storage",
      "cp",
      "--recursive",
      "dist",
      'gs://bgdk-build-for-deploy'
    ]

serviceAccount: aklapper@games-424800.iam.gserviceaccount.com

availableSecrets:
  secretManager:
  - versionName: projects/games-424800/secrets/PG_AE_URL/versions/latest
    env: 'PG_AE_URL'

# Store logs in bucket
logsBucket: 'gs://logs-cloudbuild'
options:
  logging: CLOUD_LOGGING_ONLY

# Optional: Define a timeout for the build
timeout: '1600s'

