steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'generate']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']

    # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', 'api.yaml']

serviceAccount: aklapper@games-424800.iam.gserviceaccount.com

logsBucket: 'gs://logs-cloudbuild'
options:
  logging: LEGACY

artifacts:
  objects:
    location: 'gs://bgdk-build-for-deploy'
<<<<<<< HEAD
    paths: ['**/*', '!node_modules' ]
=======
    paths: ['**/*', "!node_modules/**/*" ]
>>>>>>> fc04d944d124721ce934c90b672a35feade9c3fc
# Optional: Define a timeout for the build
timeout: '1500s'

