services:
  games-db-testing:
    build:
      context: ./apis/games-api/games-api
      dockerfile: Dockerfile.db.testing
      args:
        - POSTGRES_PASSWORD
    env_file:
      - ./apis/games-api/games-api/.env
    container_name: games-api-db-testing
    ports:
      - "5431:5432"
